#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

# Enable nbgitpuller to pull in content
jupyter serverextension enable --py nbgitpuller --sys-prefix

# Cleanup setup files
rm -rf ./*

# # Clone content branch
# ORG=CUB-Computational-Tools
# REPO=assignment_problem_set
# BRANCH=content
# git clone --single-branch --branch ${BRANCH} https://github.com/${ORG}/${REPO}.git .

# Safely remove output from all Jupyter notebooks
# find . -type f -name "*.ipynb" -exec jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace {} \+
