#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

# Remove all setup files
rm -rf ./*

# Clone content branch
git clone --single-branch --branch content https://github.com/CUB-Computational-Tools/assignment_problem_set.git .

# Safely remove output from all Jupyter notebooks
find . -type f -name "*.ipynb" -exec jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace {} \+
