#!/bin/bash

# Install JupyterLab extension
jupyter labextension install @jupyterlab/toc

# Install other python dependencies
# Note: this is only necessary if also installing R because requirements.yml is ignored in that casea
# pip install numpy matplotlib pandas